### ISSUE TITLE
Handle R53 'Alias' Records

### ISSUE THREAD

**Issue by michaelmcallister** [octodns/octodns-route53#24]
Route53 Alias records are kinda like CNAME records, but you can have them at the Apex, which as you can imagine isn't going to translate between providers very well.

They also have a different response for [list-resource-record-sets](https://docs.aws.amazon.com/cli/latest/reference/route53/list-resource-record-sets.html) (example below)

```
{
    "ResourceRecordSets": [
        {
            "AliasTarget": {
                "HostedZoneId": "Z1EXAMPLE",
                "EvaluateTargetHealth": false,
                "DNSName": "s3-website-ap-southeast-2.amazonaws.com."
            },
            "Type": "A",
            "Name": "example.com."
        },
        {
            "ResourceRecords": [
                {
                    "Value": "127.0.0.1"
                }
            ],
            "Type": "A",
            "Name": "test.example.com.",
            "TTL": 300
        },
```
See the [AWS Documentation](https://aws.amazon.com/route53/faqs/#which_dns_records_are_supported) for more info on Alias records

octodns doesn't handle this gracefully, and will throw a ``KeyError``

```
(env) ☁  dns  octodns-dump --config-file=./config/production.yaml --output-dir=./tmp example.com. route53 --debug
2017-04-30T20:17:19  [139951851439872] INFO  Manager __init__: config_file=./config/production.yaml
2017-04-30T20:17:19  [139951851439872] DEBUG Manager __init__:   configuring providers
2017-04-30T20:17:19  [139951851439872] DEBUG Route53Provider[route53] __init__: id=route53, access_key_id=***, secret_access_key=***
2017-04-30T20:17:19  [139951851439872] DEBUG Route53Provider[route53] __init__: id=route53, apply_disabled=False
2017-04-30T20:17:19  [139951851439872] INFO  Manager dump: zone=example.com., sources=()
2017-04-30T20:17:19  [139951851439872] DEBUG YamlProvider[dump] __init__: id=dump, directory=./tmp, default_ttl=3600
2017-04-30T20:17:19  [139951851439872] DEBUG YamlProvider[dump] __init__: id=dump, apply_disabled=False
2017-04-30T20:17:19  [139951851439872] DEBUG Manager configured_sub_zones: subs=[]
2017-04-30T20:17:19  [139951851439872] DEBUG Zone __init__: zone=Zone<example.com.>, sub_zones=set([])
2017-04-30T20:17:19  [139951851439872] DEBUG Route53Provider[route53] populate: name=example.com.
2017-04-30T20:17:19  [139951851439872] DEBUG Route53Provider[route53] _get_zone_id: name=example.com.
2017-04-30T20:17:19  [139951851439872] DEBUG Route53Provider[route53] r53_zones: loading
2017-04-30T20:17:20  [139951851439872] DEBUG Route53Provider[route53] _get_zone_id:   id=/hostedzone/Z3IUOSSN6JQ0DU
2017-04-30T20:17:20  [139951851439872] DEBUG Route53Provider[route53] _load_records: zone_id=/hostedzone/Z3IUOSSN6JQ0DU loading
Traceback (most recent call last):
  File "/tmp/dns/env/bin/octodns-dump", line 11, in <module>
    sys.exit(main())
  File "/tmp/dns/env/local/lib/python2.7/site-packages/octodns/cmds/dump.py", line 28, in main
    manager.dump(args.zone, args.output_dir, *args.source)
  File "/tmp/dns/env/local/lib/python2.7/site-packages/octodns/manager.py", line 330, in dump
    source.populate(zone)
  File "/tmp/dns/env/local/lib/python2.7/site-packages/octodns/provider/route53.py", line 365, in populate
    data = getattr(self, '_data_for_{}'.format(record_type))(rrset)
  File "/tmp/dns/env/local/lib/python2.7/site-packages/octodns/provider/route53.py", line 235, in _data_for_geo
    'values': [v['Value'] for v in rrset['ResourceRecords']],
KeyError: u'ResourceRecords'
(env) ☁  dns
```

**Comment by ross** [comment]
Prototyping/testing of the concepts here in https://github.com/octodns/octodns/pull/889 &amp; https://github.com/octodns/octodns-route53/pull/25
