### ISSUE TITLE
ALIAS record dump issue

### ISSUE THREAD

**Issue by web-xyz** [octodns/octodns-route53#72]
Dumped a zone with an ALIAS record.

With **version 0.0.5**, the dumped zone contains the `evaluate-target-health` and `hosted-zone-id` elements (using a **dash**).
Running a sync with the unmodified dumped zone completes correctly with no changes.

With **version 0.0.5+b10ce65c** (latest version), the dumped zone contains the `evaluate_target_health` and `hosted_zone_id` elements (using an **underscore**).
Running a sync with the unmodified dumped zone fails with validation error `service alias without hosted-zone-id`.

See below for the full outputs.

**WORKING CORRECTLY with octodns_route53 0.0.5:**
```
% octodns-dump --config-file=config/production.yaml --output-dir=config/ 'mytest.com.' route53
2023-10-16T22:06:44  [140704378021632] INFO  Manager __init__: config_file=config/production.yaml, (octoDNS 1.2.1)
2023-10-16T22:06:44  [140704378021632] INFO  Manager _config_executor: max_workers=1
2023-10-16T22:06:44  [140704378021632] INFO  Manager _config_include_meta: include_meta=False
2023-10-16T22:06:44  [140704378021632] INFO  Manager _config_auto_arpa: auto_arpa=False
2023-10-16T22:06:44  [140704378021632] INFO  Manager __init__: global_processors=[]
2023-10-16T22:06:44  [140704378021632] INFO  Manager __init__: global_post_processors=[]
2023-10-16T22:06:44  [140704378021632] INFO  Manager __init__: provider=config (octodns.provider.yaml 1.2.1)
2023-10-16T22:06:44  [140704378021632] INFO  botocore.credentials Found credentials in environment variables.
2023-10-16T22:06:44  [140704378021632] INFO  Manager __init__: provider=route53 (octodns_route53 0.0.5)
2023-10-16T22:06:44  [140704378021632] INFO  Manager dump: zone=mytest.com., output_dir=config/, output_provider=None, lenient=False, split=False, sources=['route53']
2023-10-16T22:06:44  [140704378021632] INFO  Manager dump: using custom YamlProvider
2023-10-16T22:06:45  [140704378021632] INFO  Route53Provider[route53] populate:   found 2 records, exists=True
2023-10-16T22:06:45  [140704378021632] INFO  YamlProvider[dump] plan: desired=mytest.com.
2023-10-16T22:06:45  [140704378021632] INFO  YamlProvider[dump] plan:   Creates=2, Updates=0, Deletes=0, Existing Records=0
2023-10-16T22:06:45  [140704378021632] INFO  YamlProvider[dump] apply: making 2 changes to mytest.com.


% cat config/mytest.com.yaml                                                                  
---
? ''
: ttl: 172800
  type: NS
  values:
  - test.co.uk.
  - test.com.
  - test.net.
  - test.org.
myalias:
  ttl: 942942942
  type: Route53Provider/ALIAS
  value:
    evaluate-target-health: false
    hosted-zone-id: Z2FDTNDATAQYW2
    name: xxx.cloudfront.net.
    type: A


% octodns-sync --config-file=config/production.yaml 
2023-10-16T22:07:18  [140704378021632] INFO  Manager __init__: config_file=config/production.yaml, (octoDNS 1.2.1)
2023-10-16T22:07:18  [140704378021632] INFO  Manager _config_executor: max_workers=1
2023-10-16T22:07:18  [140704378021632] INFO  Manager _config_include_meta: include_meta=False
2023-10-16T22:07:18  [140704378021632] INFO  Manager _config_auto_arpa: auto_arpa=False
2023-10-16T22:07:18  [140704378021632] INFO  Manager __init__: global_processors=[]
2023-10-16T22:07:18  [140704378021632] INFO  Manager __init__: global_post_processors=[]
2023-10-16T22:07:18  [140704378021632] INFO  Manager __init__: provider=config (octodns.provider.yaml 1.2.1)
2023-10-16T22:07:18  [140704378021632] INFO  botocore.credentials Found credentials in environment variables.
2023-10-16T22:07:18  [140704378021632] INFO  Manager __init__: provider=route53 (octodns_route53 0.0.5)
2023-10-16T22:07:18  [140704378021632] INFO  Manager sync: eligible_zones=[], eligible_targets=[], dry_run=True, force=False, plan_output_fh=<stdout>
2023-10-16T22:07:18  [140704378021632] INFO  Manager sync:   zone=mytest.com.
2023-10-16T22:07:18  [140704378021632] INFO  Manager sync:   sources=['config']
2023-10-16T22:07:18  [140704378021632] INFO  Manager sync:   targets=['route53']
2023-10-16T22:07:18  [140704378021632] INFO  YamlProvider[config] populate:   found 2 records, exists=False
2023-10-16T22:07:18  [140704378021632] INFO  Route53Provider[route53] plan: desired=mytest.com.
2023-10-16T22:07:19  [140704378021632] INFO  Route53Provider[route53] populate:   found 2 records, exists=True
2023-10-16T22:07:19  [140704378021632] INFO  Route53Provider[route53] plan:   No changes
2023-10-16T22:07:19  [140704378021632] INFO  Plan 
********************************************************************************
No changes were planned
********************************************************************************
```

**NOT WORKING CORRECTLY with octodns_route53 0.0.5+b10ce65c**
```
% octodns-dump --config-file=config/production.yaml --output-dir=config/ 'mytest.com.' route53
2023-10-16T22:12:28  [140704378021632] INFO  Manager __init__: config_file=config/production.yaml, (octoDNS 1.2.1)
2023-10-16T22:12:28  [140704378021632] INFO  Manager _config_executor: max_workers=1
2023-10-16T22:12:28  [140704378021632] INFO  Manager _config_include_meta: include_meta=False
2023-10-16T22:12:28  [140704378021632] INFO  Manager _config_auto_arpa: auto_arpa=False
2023-10-16T22:12:28  [140704378021632] INFO  Manager __init__: global_processors=[]
2023-10-16T22:12:28  [140704378021632] INFO  Manager __init__: global_post_processors=[]
2023-10-16T22:12:28  [140704378021632] INFO  Manager __init__: provider=config (octodns.provider.yaml 1.2.1)
2023-10-16T22:12:28  [140704378021632] INFO  Route53Provider[route53] __init__: id=route53, access_key_id=None, max_changes=1000, delegation_set_id=None, get_zones_by_name=False
2023-10-16T22:12:28  [140704378021632] INFO  botocore.credentials Found credentials in environment variables.
2023-10-16T22:12:28  [140704378021632] INFO  Manager __init__: provider=route53 (octodns_route53 0.0.5+b10ce65c)
2023-10-16T22:12:28  [140704378021632] INFO  Manager dump: zone=mytest.com., output_dir=config/, output_provider=None, lenient=False, split=False, sources=['route53']
2023-10-16T22:12:28  [140704378021632] INFO  Manager dump: using custom YamlProvider
2023-10-16T22:12:29  [140704378021632] INFO  Route53Provider[route53] populate:   found 2 records, exists=True
2023-10-16T22:12:29  [140704378021632] INFO  YamlProvider[dump] plan: desired=mytest.com.
2023-10-16T22:12:29  [140704378021632] INFO  YamlProvider[dump] plan:   Creates=2, Updates=0, Deletes=0, Existing Records=0
2023-10-16T22:12:29  [140704378021632] INFO  YamlProvider[dump] apply: making 2 changes to mytest.com.


% cat config/mytest.com.yaml                                                                  
---
? ''
: ttl: 172800
  type: NS
  values:
  - test.co.uk.
  - test.com.
  - test.net.
  - test.org.
myalias:
  ttl: 942942942
  type: Route53Provider/ALIAS
  value:
    evaluate_target_health: false
    hosted_zone_id: Z2FDTNDATAQYW2
    name: xxx.cloudfront.net.
    type: A


% octodns-sync --config-file=config/production.yaml
2023-10-16T22:13:05  [140704378021632] INFO  Manager __init__: config_file=config/production.yaml, (octoDNS 1.2.1)
2023-10-16T22:13:05  [140704378021632] INFO  Manager _config_executor: max_workers=1
2023-10-16T22:13:05  [140704378021632] INFO  Manager _config_include_meta: include_meta=False
2023-10-16T22:13:05  [140704378021632] INFO  Manager _config_auto_arpa: auto_arpa=False
2023-10-16T22:13:05  [140704378021632] INFO  Manager __init__: global_processors=[]
2023-10-16T22:13:05  [140704378021632] INFO  Manager __init__: global_post_processors=[]
2023-10-16T22:13:05  [140704378021632] INFO  Manager __init__: provider=config (octodns.provider.yaml 1.2.1)
2023-10-16T22:13:06  [140704378021632] INFO  Route53Provider[route53] __init__: id=route53, access_key_id=None, max_changes=1000, delegation_set_id=None, get_zones_by_name=False
2023-10-16T22:13:06  [140704378021632] INFO  botocore.credentials Found credentials in environment variables.
2023-10-16T22:13:06  [140704378021632] INFO  Manager __init__: provider=route53 (octodns_route53 0.0.5+b10ce65c)
2023-10-16T22:13:06  [140704378021632] INFO  Manager sync: eligible_zones=[], eligible_targets=[], dry_run=True, force=False, plan_output_fh=<stdout>
2023-10-16T22:13:06  [140704378021632] INFO  Manager sync:   zone=mytest.com.
2023-10-16T22:13:06  [140704378021632] INFO  Manager sync:   sources=['config']
2023-10-16T22:13:06  [140704378021632] INFO  Manager sync:   targets=['route53']
Traceback (most recent call last):
  File "/private/tmp/dns-latest/env/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/private/tmp/dns-latest/env/lib/python3.11/site-packages/octodns/cmds/sync.py", line 57, in main
    manager.sync(
  File "/private/tmp/dns-latest/env/lib/python3.11/site-packages/octodns/manager.py", line 694, in sync
    ps, d = future.result()
            ^^^^^^^^^^^^^^^
  File "/private/tmp/dns-latest/env/lib/python3.11/site-packages/octodns/manager.py", line 60, in result
    return self.func(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/dns-latest/env/lib/python3.11/site-packages/octodns/manager.py", line 439, in _populate_and_plan
    source.populate(zone, lenient=lenient)
  File "/private/tmp/dns-latest/env/lib/python3.11/site-packages/octodns/provider/yaml.py", line 362, in populate
    self._populate_from_file(source, zone, lenient)
  File "/private/tmp/dns-latest/env/lib/python3.11/site-packages/octodns/provider/yaml.py", line 314, in _populate_from_file
    record = Record.new(
             ^^^^^^^^^^^
  File "/private/tmp/dns-latest/env/lib/python3.11/site-packages/octodns/record/base.py", line 82, in new
    raise ValidationError(fqdn, reasons, context)
octodns.record.exception.ValidationError: Invalid record "myalias.mytest.com.", ./config/mytest.com.yaml, line 11, column 3
  - service alias without hosted-zone-id
```

**Comment by ross** [comment]
Unfortunately it's been a long time since a release was cut and there's a decent chunk of changes diff-wise, but there hasn't been ALL that much change to actual code. A refactor does unfortunately complicate seeing that, but as the WIP changelog indicates there's been no real changes. 

https://github.com/octodns/octodns-route53/compare/v0.0.5...main

I don't see anything directly related to `evaluate-target-health` so what's changed may lie elsewhere. I'll see if I can reproduce.

**Comment by ross** [comment]
Been a minute since I made use of git bisect, but it worked perfectly here. 

```console
$ git bisect start
...
$ git bisect good v0.0.5
...
$ git bisect bad HEAD
...
$ git bisect good
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[775a760bdc8fd5d0437f453acfb2901900f6c9de] Convert _Route53AliasValue to dict-based
...
$ git bisect bad
775a760bdc8fd5d0437f453acfb2901900f6c9de is the first bad commit
commit 775a760bdc8fd5d0437f453acfb2901900f6c9de
Author: Ross McFarland <rwmcfa1@gmail.com>
Date:   Tue Oct 25 19:09:15 2022 -0700

    Convert _Route53AliasValue to dict-based

 octodns_route53/record.py              | 41 ++++++++++++++++++++++++++++------
 tests/test_octodns_provider_route53.py | 14 +++++++-----
 2 files changed, 42 insertions(+), 13 deletions(-)
```

Commit that made the change: https://github.com/octodns/octodns-route53/pull/41
